spring:
  #  ˝æ›ø‚≈‰÷√
  datasource:
    username: root
    password: moranxiangai0702
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver